[리뷰만 부탁드립니다] posting 작성과 post_detail_view 작성했습니다.
wecode-bootcamp-korea/15-1st-Crazytrain-backend pull request #10
Opened 2020-12-22 08:29 UTC by mincheolkk

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 글쓰기 기능 구현
- 작성 글들 디테일 뷰 구현
		 
## 수정 사항들 자세한 내용
- 한줄 요약과 비슷합니다

## 기타 질문 및 특이 사항
- Null = True 인 요소들이 Null 로 들어올 때, Null 값을 어떻게 출력할 수 있을까요 ? 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-22 13:49 UTC, ulfrid requested changes
수정 부탁드립니다.

2020-12-22 13:49 UTC, ulfrid commented on community/views.py
>  from django.shortcuts import render
안쓰는건 제거 부탁드립니다.

2020-12-22 13:49 UTC, ulfrid commented on community/views.py
> +#from user.utils import login_decorator
로그인 데코레이터 머지 됐으니 적용 부탁드립니다.

2020-12-22 13:49 UTC, ulfrid commented on community/views.py
> +        user_id      = 2
이런식의 수동적 코드는 머지될수 없습니다. 코드를 더 완성해서 PR요청 바랍니다.

2020-12-22 13:49 UTC, ulfrid commented on community/views.py
> +            post = Post.objects.all().last()
```suggestion
           post = Post.objects.create(
                user_id=user_id,
                house_size_id=house_size,
                house_style_id=house_style,
                housing_type_id=housing_type
            )
```
최근 생성된걸 관리하려면 바로 담으면 가능합니다.

2020-12-22 13:49 UTC, ulfrid commented on community/views.py
> +                )
```suggestion
           post_block = [ 
                PostBlock(
                    image=item["image"],
                    content=item["content"],
                    space_id = item["space"],
                    post_id=post.id,
                ) for item in block
            ] 
            PostBlock.objects.bulk_create(post_block)
```
반복문 구현시 i 같은 변수 사용은 지양해 주세요!
블록 갯수만큼 생성하시는 거라면 bulk_create()를 사용해주세요. 
https://docs.djangoproject.com/en/3.1/ref/models/querysets/#bulk-create

2020-12-22 13:49 UTC, ulfrid commented on community/views.py
> +            user  = User.objects.get(id=post.user_id)
post 모델에는 user_id가 있다면 굳이 이렇게 담지 않아도 됩니다. 
post.user.id , post.user.nickname, post.user.profile_image 등 정참조라면 바로 접근이 가능합니다!

2020-12-22 13:49 UTC, ulfrid commented on community/views.py
> +                housing_type = ' '
이부분 들도 위에서 처럼 post에 전부 정참조 연결이라면 
post.house_size.size 라는 접근이 가능할테니 변경해주세요.

2020-12-22 13:49 UTC, ulfrid commented on community/views.py
> +                        },
위의 리뷰를 참고해서 이부분들의 접근을 다시 변경해보세요.

2020-12-24 01:55 UTC, ulfrid requested changes

2020-12-24 01:55 UTC, ulfrid commented on community/views.py
> +                            }
이렇게 다 하나하나 딕셔너리로 분리 하는 이유가 있을까요?

2020-12-24 02:00 UTC, mincheolkk commented on community/views.py
> +                            }
안녕하세요 위 로직은 프론트요청에따라서 분리해서 입력했습니다

2020-12-24 03:05 UTC, ulfrid commented
LGTM.

2020-12-24 03:06 UTC, merged