[오늘의집] 석여주 - signup관련 설정
wecode-bootcamp-korea/15-1st-Crazytrain-backend pull request #4
Opened 2020-12-18 06:54 UTC by YEOJU-SEOK

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 오늘의집 회원가입 화면 구성했습니다
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-email validation,password validation관련 적용했습니다

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- email,password의 경우 위스타그램에서 해본적이 있어서 정규화를 적용했는데요, 
닉네임은 정규화를 적용하지 않았는데, 혹시 꼭 정규화를 해야할 필요가 있는걸까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-18 08:09 UTC, lordmyshepherd requested changes

2020-12-18 08:09 UTC, lordmyshepherd commented on user/models.py
> +    note          = models.CharField(max_length=50, null=True, blank=True)
`null=True`와 `blank=True` 속성을 동시에 사용하시는 이유가 있나요?

2020-12-18 08:09 UTC, lordmyshepherd commented on user/urls.py
> +   # path('/signin', Signin.as_view())
불필요한 주석은 지워주세요~
```suggestion

```

2020-12-18 08:09 UTC, lordmyshepherd commented on user/views.py
> +                )
한줄로 수정해주세요. 이 경우에는 오히려 줄을 나누는게 가독성을 안좋게 만드는 것 같습니다!

2020-12-18 08:09 UTC, lordmyshepherd commented on user/views.py
> +                )
마찬가지 입니다.

2020-12-18 08:09 UTC, lordmyshepherd commented on user/views.py
> +                )
마찬가지 입니다.

2020-12-18 08:09 UTC, lordmyshepherd commented on user/views.py
> +                )
마찬가지 입니다.

2020-12-18 08:09 UTC, lordmyshepherd commented on user/views.py
> +                )
마찬가지 입니다.

2020-12-18 08:09 UTC, lordmyshepherd commented on user/views.py
> +                )
마찬가지 입니다.

2020-12-18 08:09 UTC, lordmyshepherd commented on user/views.py
> +            )
마찬가지입니다.

2020-12-18 08:09 UTC, lordmyshepherd commented on user/views.py
> +                )
```suggestion
                User.objects.create(
                    email    = data['email'],
                    password = bcrypt.hashpw(data['password'].encode('utf-8'), bcrypt.gensalt()).decode(),
                    nickname = data['nickname']
                )
                return JsonResponse(
                    {"message":"SUCCESS"},status=201
                )
```

2020-12-18 08:54 UTC, YEOJU-SEOK commented on user/models.py
> +    note          = models.CharField(max_length=50, null=True, blank=True)
blank와 null값의 사용용도가 다르다고 생각했습니다. blank를 지정하지 않을경우 false가 되는데 이부분이 문제가 될거같아서 사전에 작성해두었습니다. 간단히 검색했을때 null/blank모두 true로 설정을 해주는게 일반적이라고 해서 적용해 보았습니다. 회원가입에 관계가 없다면 삭제를 하겠습니다.(제가 db에 관련된 개념이 null이고, blank는 유효성검사 관련이라고 이해하고 있는데 올바른 접근방법일까요?)

2020-12-20 13:05 UTC, ulfrid requested changes

2020-12-21 12:29 UTC, ulfrid commented
LGTM.

2020-12-21 12:29 UTC, merged