15기 이수한 [오늘의 집] 스토어 카테고리 사이드바 api 작성
wecode-bootcamp-korea/15-1st-Crazytrain-backend pull request #5
Opened 2020-12-19 05:53 UTC by dltngks54

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)

프론트엔드에게 카테고리와 서브카테고리 정보를 전달해 주는 api를 작성 하였습니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

prefetch_related를 사용하여 카테고리 하나가 갖고있는 여러한 서브 카테고리를 함께 보내 주었습니다.
(프론트한테 보내는 JsonResponse 데이터는 프론트분이 원하는 양식대로 맞춰 진행했습니다.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

prefetch_related라는 개념을 구글링을 통하여 새롭게 알게 되었는데

카테고리와 서브카테고리를 함께 보낼때 사용하는 것이 올바른 용도인지 궁금합니다. (데이터 관계가 1:N인 경우)
(데이터는 잘 보내졌습니다!)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-20 10:31 UTC, ulfrid requested changes

2020-12-20 10:31 UTC, ulfrid commented on menu/views.py
> +             return JsonResponse({'message':'ERROR'}, status=400)
```suggestion
         except:
             return JsonResponse({'message':'ERROR'}, status=400)
```
위와 같은 익셉션이 발생하면 무조건 400 및 에러 처리를 하는 것은 제일 하지 말아야 할 처리입니다.
여러분이 익셉션을 사용하는것은 500 에러가 났을 경우, 정확한 에러케이스를 캐치해서 적절한 리턴을 하기 위함인데, 
위와 같이 처리하면 500 에러가 나도 클라이언트에게 잘못을 전가함과 동시에 본인의 정확한 에러도 찾을 수 없는 무책임한 코드 입니다.
앞으로 진행하는 코드에서는 이런 코드는 절대 사용하지 마세요.

2020-12-20 10:31 UTC, ulfrid commented on menu/views.py
> +             return JsonResponse({'message':'VALUE_ERROR'}, status=400)
```suggestion
         except ValueError:
             return JsonResponse({'message':'VALUE_ERROR'}, status=400)
```
위의 ValueError케이스가 날 수 있는 경우가 무엇 일까요?

2020-12-20 10:31 UTC, ulfrid commented on menu/views.py
> +            } for category in categories]
```suggestion
            if categories.exists():   
                categories = [{ 
                 'categoryId'    :  category.id,
                 'category'      :  category.name,
                 'subCategories' : [
                     sub_category.name
                for sub_category in category.subcategory_set.all()]
            } for category in categories]
```
인덴트 잘 정리해주세요

2020-12-21 07:30 UTC, dltngks54 commented on menu/views.py
> +             return JsonResponse({'message':'VALUE_ERROR'}, status=400)
발생할 수 없는 에러인것 같습니다. 불필요하다고 생각하여 수정하겠습니다!

2020-12-21 07:31 UTC, dltngks54 commented on menu/views.py
> +             return JsonResponse({'message':'ERROR'}, status=400)
감사합니다 수정하겠습니다

2020-12-21 12:33 UTC, ulfrid commented on menu/views.py
> +             return JsonResponse({'message':'VALUE_ERROR'}, status=400)
아마도 타입이 다른 에러가 들어가면 날것 같은데, 이렇게 익셉션 처리를 하던지 아니면  타입 검사를 해서 TypeError를 raise 하는게 더 좋을것 같습니다.

2020-12-21 13:16 UTC, merged

2020-12-21 13:16 UTC, ulfrid commented
LGTM.